export default {
    nav:{
        offers:'Offers',
        leaderboard:'Leaderboard',
        statistics:'My Statistics',
        teamStatistics:'Team Statistics',
        team:'Team'
    },
    offers:{
        addmark:'Add Mark',
        markuser:'Mark User',
        markcontent:'Mark Content',
        marktime:'Mark Time',
        mark:'Mark',
        feature:'Featured Surveys',
        partner:'Offer Partners',
        wall:'Discount Wall',
        quota:'Quota',
        start:'Start',
        copy:'Copy',
        sortBy:'Sort By',
        recentUpdate:'Recent Update',
        recentCreate:'Recent Create',
        highestReward:'Highest Reward',
        lowestReward:'Lowest Reward',
        pid:'PID',
        name:'Name',
        country:'Country',
        countryCode:'Country Code',
        loi:'Loi',
        ir:'Ir',
        rewardCoins:'Reward Coins',
        createTime:'Createtime',
        updateTime:'Updatetime',
        operate:'Operate'
    },
    leaderboard:{
        dailyLeaderboard:'Daily Leaderboard',
        weeklyLeaderboard:'Weekly Leaderboard',
        monthlyLeaderboard:'Monthly Leaderboard',
        daily:'Daily',
        weekly:'Weekly',
        monthly:'Monthly'
    },
    statistics:{
        coins:'Coins',
        usd:'USD',
        completeOffers:'Completed Offers',
        completedOffers:'Completed Offers',
        offerEarnings:'Offer Earnings',
        pendingEarnings:'Pending Earnings',
        failedEarnings:'Failed Earnings',
        tooshort:'The participation interval is too short',
        status:'Status',
        rewardCoins:'Reward',
        record:'Reply Record',
        pending:'Pending',
        success:'Success',
        deduction:'Deduction',
        failure:'Failed',
        overQuota:'Over Quota',
        quota:'Quota',
        terminate:'Terminate',
        overview:'Overview',
        platform:'Platform',
        projectNo:'Project No',
        projectName:'Project Name',
        ip:'IP',
        memberPayout:'Member Payout',
        teamPayout:'Team Payout',
        auditStatus:'Audit Status',
        time:'Time',
        search:'Search',
        startDate:'Start Date',
        endDate:'End Date',
        export:'Export',
        teamEarnings:'Team Earnings',
        memberEarnings:'Member Earnings',
        teamPending:'Team Pending',
        teamDeduction:'Team Deduction',
        memberDeduction:'Member Deduction',
        memberPending:'Member Pending',
        teamFailed:'Team Failed',
        memberFailed:'Member Failed',
        member:'Member',
        teamRewardCoins:'Team Rewards',
        memberRewardCoins:'Member Rewards',
        nickname:'Member Nickname', 
    },
    user:{
        allread:'All Read',
        markread:'Mark Read',
        message:'Internal Message',
        addUser:'ADD TEAM USER',
        editUser:'EDIT TEAM USER',
        changeNickname:'Change Nickname',
        avatar:'Avatar',
        role:'Role',
        username:'Username',
        password:'Password',
        nickname:'Nickname',
        commissionRatio:'Commission Ratio',
        submit:'Submit',
        edit:'Edit',
        add:'Add',
        save:'Save',
        loginIp:'Login IP',
        loginTime:'Login Time',
        lastLoginTime:'Last Login Time',
        operate:'Operate',
        notFill:'Not filled in, default not modified',
        searchByNickname:'Search By Nickname',
        profile:'Profile',
        logout:'Logout',
        coinsEarned:'Coins Earned',
        usdEarned:'USD Earned',
        earnings:'Earnings',
        last7Days:'Last 7 Days',
        yourInfo:'Your Info',
        memberId:'MemberID',
        group:'Group',
        team:'Team',
        loginRegion:'Login Region',
        email:'Email',
        settings:'Settings',
        changeDisplayName:'Change Display Name',
        editDisplayName:'Edit Display Name',
        change:'Change',
        recentOffers:'Recent Offers'
    }
  }